name = "temp-email-pages"
pages_build_output_dir = "../frontend/dist"
compatibility_date = "2026-03-16"

[[services]]
binding = "BACKEND"
service = "cloudflare_temp_email"
# 如果你的 Worker 配置了命名环境，再取消注释并改成实际环境名
# environment = "production"
